### ISSUE TITLE
[1.17.1] Hammer & Excavator Durability

### ISSUE THREAD

**Issue by Ducri** [kwpugh/EmeraldTools#9] opened 2021-07-08 15:57 UTC
Hi,

Just to query as to if the Hammer and Excavator's durability is bugged or intentionally made so that they do not really break.
I have started "Better Minecraft by "SharkieFPS" on Curseforge and have tried your latest Fabric version of the mod is well and both of these do not appear to directly affect the durability of the tools when in use. The Hammer only appears to have some durability removed when mining non-stone related blocks like Dirt etc. Not an issue if this is intentional and more say for landscaping but is quite overpowered and doesnt suit the game well in my opinion.  Can this be clarified as intentional design or fixed please?

**Comment by kwpugh** [comment] 2021-07-08 16:01
Which version of the mod are you using?

**Comment by Ducri** [comment] 2021-07-08 16:04
Currently. "EmeraldTools-Fabric-1.17-1.2.18"

**Comment by kwpugh** [comment] 2021-07-08 16:05
There was some issue in v18.   Please v19.

**Comment by Ducri** [comment] 2021-07-08 16:11
Just did, that has made no difference, unfortunately.

**Comment by kwpugh** [comment] 2021-07-08 16:57
Hmmm, I have been playing and using the hammers and excavators and they do indeed take damage.   Perhaps there is some in the mudpack that is interfering.   I will take a look at the latest modpack and see if I notice it.

**Comment by kwpugh** [comment] 2021-07-08 18:16
I cannot replicate this on my end, all the hammers and excavators take 1 point of damage with each use.   Did you install any other mods to the standard Better Minecraft pack?

**Comment by Ducri** [comment] 2021-07-08 20:26
I havent used any external mods, to note I am playing on Better Minecraft [FABRIC RELEASE] V1. This problem also occurs on other versions of the pack for Fabric. I have uninstalled and reinstalled the pack as a whole twice as well in testing and this is still occurring. It may be an issue on my end but I havent done anything to provoke it, no modification of the game or its files. Always played on a fresh install.

**Comment by kwpugh** [comment] 2021-07-08 20:29
I don't think it is on your end.  I installed a copy of latest Better Minecraft and the hammers and excavators do not take damage.  Changed to a more recent version of Emerald Tools and still no damage.   Using Emerald Tools in other packs and stand alone and they take damage.  There is something in the Better Minecraft that is causing it.

Still looking.

**Comment by Ducri** [comment] 2021-07-08 20:36
Thanks, glad to hear that you've managed to replicate it. So odd it is happening. Glad I brought it to your attention

**Comment by kwpugh** [comment] 2021-07-08 21:34
I have reached out to Sparkle to see what they think.  Will update if I find anything new.

**Comment by kwpugh** [comment] 2021-07-09 02:41
So, Sparkie figured it out with some trial and error.Turns out it is the Slab Helper mod.  It does a mixin that is messing with the hammer and excavator.  Surprised me, but after looking at the source I see where the issue is.   Sparkie is handling it from here, so I am closing this out.

**Closed as completed by kwpugh** 2021-07-09 02:41 UTC
Labels: bug
